/**
 * Starter curriculum: colloquial spoken Tamil for English/Spanish speakers.
 * Transliterations are a practical learner-friendly romanization, not IAST.
 */
export const rawCurriculum = {
  version: 1,
  localeDefault: 'en',
  items: [
    {
      id: 'vanakkam',
      tamil: 'வணக்கம்',
      transliteration: 'vaṇakkam',
      englishMeaning: 'Hello; greetings',
      spanishMeaning: 'Hola; saludos',
      englishApproxPronunciation: 'vuh-NAK-kum',
      spanishApproxPronunciation: 'ban-AK-kam',
      partOfSpeech: 'phrase',
      tags: ['greetings', 'stage-1'],
      frequencyPriority: 1,
      difficulty: 1,
      exampleSentence: {
        tamil: 'வணக்கம், எப்படி இருக்கீங்க?',
        transliteration: 'Vaṇakkam, eppaṭi irukkīṅka?',
        english: 'Hello, how are you?',
        spanish: 'Hola, ¿cómo estás?',
      },
      registerNote: 'Neutral polite; safe with most people.',
    },
    {
      id: 'eppadi-irukeenga',
      tamil: 'எப்படி இருக்கீங்க?',
      transliteration: 'eppaṭi irukkīṅga?',
      englishMeaning: 'How are you? (polite)',
      spanishMeaning: '¿Cómo estás? (de cortesía)',
      englishApproxPronunciation: 'EP-puh-dee i-ruk-KEENG-gah',
      spanishApproxPronunciation: 'EP-pa-di i-ruk-KIN-ga',
      partOfSpeech: 'phrase',
      tags: ['greetings', 'stage-1'],
      frequencyPriority: 2,
      difficulty: 2,
    },
    {
      id: 'nalla-irukken',
      tamil: 'நல்லா இருக்கேன்',
      transliteration: 'nallā irukkēṉ',
      englishMeaning: "I'm fine (colloquial)",
      spanishMeaning: 'Estoy bien (coloquial)',
      englishApproxPronunciation: 'NAL-la i-RUK-kayn',
      spanishApproxPronunciation: 'NA-la i-RUK-ken',
      partOfSpeech: 'phrase',
      tags: ['greetings', 'stage-1'],
      frequencyPriority: 3,
      difficulty: 2,
    },
    {
      id: 'sari',
      tamil: 'சரி',
      transliteration: 'cari',
      englishMeaning: 'OK; alright',
      spanishMeaning: 'Vale; bien',
      englishApproxPronunciation: 'SUH-ree',
      spanishApproxPronunciation: 'SA-ri',
      partOfSpeech: 'phrase',
      tags: ['greetings', 'stage-1'],
      frequencyPriority: 4,
      difficulty: 1,
    },
    {
      id: 'aama',
      tamil: 'ஆமா',
      transliteration: 'āmā',
      englishMeaning: 'Yes (spoken)',
      spanishMeaning: 'Sí (coloquial)',
      englishApproxPronunciation: 'AA-maa',
      spanishApproxPronunciation: 'A-ma',
      partOfSpeech: 'phrase',
      tags: ['basics', 'stage-1'],
      frequencyPriority: 5,
      difficulty: 1,
    },
    {
      id: 'illa',
      tamil: 'இல்ல',
      transliteration: 'illa',
      englishMeaning: 'No; not (spoken)',
      spanishMeaning: 'No; no es',
      englishApproxPronunciation: 'IL-la',
      spanishApproxPronunciation: 'I-la',
      partOfSpeech: 'phrase',
      tags: ['basics', 'stage-1'],
      frequencyPriority: 6,
      difficulty: 1,
    },
    {
      id: 'nandri',
      tamil: 'நன்றி',
      transliteration: 'naṉṟi',
      englishMeaning: 'Thank you',
      spanishMeaning: 'Gracias',
      englishApproxPronunciation: 'NAN-dree',
      spanishApproxPronunciation: 'NAN-dri',
      partOfSpeech: 'phrase',
      tags: ['polite', 'stage-1'],
      frequencyPriority: 7,
      difficulty: 1,
    },
    {
      id: 'mannikavum',
      tamil: 'மன்னிக்கவும்',
      transliteration: 'maṉṉikkavum',
      englishMeaning: 'Sorry; excuse me',
      spanishMeaning: 'Perdón; disculpa',
      englishApproxPronunciation: 'mun-ni-KKA-vum',
      spanishApproxPronunciation: 'ma-ni-KA-bum',
      partOfSpeech: 'phrase',
      tags: ['polite', 'stage-1'],
      frequencyPriority: 8,
      difficulty: 2,
    },
    {
      id: 'thayavu-seithu',
      tamil: 'தயவுசெய்து',
      transliteration: 'tayavu ceytu',
      englishMeaning: 'Please',
      spanishMeaning: 'Por favor',
      englishApproxPronunciation: 'thuh-yuh-SEY-dhu',
      spanishApproxPronunciation: 'ta-ya-bu-SEI-du',
      partOfSpeech: 'phrase',
      tags: ['polite', 'stage-1'],
      frequencyPriority: 9,
      difficulty: 2,
    },
    {
      id: 'naan',
      tamil: 'நான்',
      transliteration: 'nāṉ',
      englishMeaning: 'I',
      spanishMeaning: 'Yo',
      englishApproxPronunciation: 'NAHN',
      spanishApproxPronunciation: 'nan',
      partOfSpeech: 'pronoun',
      tags: ['pronouns', 'stage-1'],
      frequencyPriority: 10,
      difficulty: 1,
    },
    {
      id: 'neenga',
      tamil: 'நீங்க',
      transliteration: 'nīṅka',
      englishMeaning: 'You (polite/plural)',
      spanishMeaning: 'Usted(es)',
      englishApproxPronunciation: 'NEENG-gah',
      spanishApproxPronunciation: 'NIN-ga',
      partOfSpeech: 'pronoun',
      tags: ['pronouns', 'stage-1'],
      frequencyPriority: 11,
      difficulty: 1,
    },
    {
      id: 'naanga',
      tamil: 'நாங்க',
      transliteration: 'nāṅka',
      englishMeaning: 'We (colloquial)',
      spanishMeaning: 'Nosotros (coloquial)',
      englishApproxPronunciation: 'NAANG-gah',
      spanishApproxPronunciation: 'NAN-ga',
      partOfSpeech: 'pronoun',
      tags: ['pronouns', 'stage-1'],
      frequencyPriority: 12,
      difficulty: 2,
    },
    {
      id: 'avanga',
      tamil: 'அவங்க',
      transliteration: 'avaṅka',
      englishMeaning: 'They; he/she (respectful colloquial)',
      spanishMeaning: 'Ellos/as; él/ella (coloquial respetuoso)',
      englishApproxPronunciation: 'uh-VUNG-gah',
      spanishApproxPronunciation: 'a-BAN-ga',
      partOfSpeech: 'pronoun',
      tags: ['pronouns', 'stage-1'],
      frequencyPriority: 13,
      difficulty: 2,
    },
    {
      id: 'idhu',
      tamil: 'இது',
      transliteration: 'itu',
      englishMeaning: 'This',
      spanishMeaning: 'Esto; este',
      englishApproxPronunciation: 'I-dhu',
      spanishApproxPronunciation: 'I-du',
      partOfSpeech: 'pronoun',
      tags: ['deixis', 'stage-1'],
      frequencyPriority: 14,
      difficulty: 1,
    },
    {
      id: 'adhu',
      tamil: 'அது',
      transliteration: 'atu',
      englishMeaning: 'That',
      spanishMeaning: 'Eso; ese',
      englishApproxPronunciation: 'UH-dhu',
      spanishApproxPronunciation: 'A-du',
      partOfSpeech: 'pronoun',
      tags: ['deixis', 'stage-1'],
      frequencyPriority: 15,
      difficulty: 1,
    },
    {
      id: 'inga',
      tamil: 'இங்க',
      transliteration: 'iṅka',
      englishMeaning: 'Here',
      spanishMeaning: 'Aquí',
      englishApproxPronunciation: 'ING-gah',
      spanishApproxPronunciation: 'IN-ga',
      partOfSpeech: 'adverb',
      tags: ['deixis', 'stage-1'],
      frequencyPriority: 16,
      difficulty: 1,
    },
    {
      id: 'anga',
      tamil: 'அங்க',
      transliteration: 'aṅka',
      englishMeaning: 'There',
      spanishMeaning: 'Allí',
      englishApproxPronunciation: 'UNG-gah',
      spanishApproxPronunciation: 'AN-ga',
      partOfSpeech: 'adverb',
      tags: ['deixis', 'stage-1'],
      frequencyPriority: 17,
      difficulty: 1,
    },
    {
      id: 'poren',
      tamil: 'போறேன்',
      transliteration: 'pōrēṉ',
      englishMeaning: "I'm going (colloquial)",
      spanishMeaning: 'Me voy (coloquial)',
      englishApproxPronunciation: 'POH-rayn',
      spanishApproxPronunciation: 'PO-reng',
      partOfSpeech: 'phrase',
      tags: ['verbs', 'stage-1'],
      frequencyPriority: 20,
      difficulty: 2,
    },
    {
      id: 'vareen',
      tamil: 'வரேன்',
      transliteration: 'varēṉ',
      englishMeaning: "I'll come (colloquial)",
      spanishMeaning: 'Voy a venir (coloquial)',
      englishApproxPronunciation: 'vuh-RAYN',
      spanishApproxPronunciation: 'ba-REN',
      partOfSpeech: 'phrase',
      tags: ['verbs', 'stage-1'],
      frequencyPriority: 21,
      difficulty: 2,
    },
    {
      id: 'venum',
      tamil: 'வேணும்',
      transliteration: 'vēṇum',
      englishMeaning: 'Want; need (soft, colloquial)',
      spanishMeaning: 'Quiero; necesito (suave)',
      englishApproxPronunciation: 'VAY-num',
      spanishApproxPronunciation: 'BE-num',
      partOfSpeech: 'verb',
      tags: ['verbs', 'stage-1'],
      frequencyPriority: 22,
      difficulty: 2,
    },
    {
      id: 'saapadu',
      tamil: 'சாப்பாடு',
      transliteration: 'cāppāṭu',
      englishMeaning: 'Food; meal (colloquial)',
      spanishMeaning: 'Comida (coloquial)',
      englishApproxPronunciation: 'SAH-pah-du',
      spanishApproxPronunciation: 'SA-pa-du',
      partOfSpeech: 'noun',
      tags: ['food', 'stage-1'],
      frequencyPriority: 30,
      difficulty: 2,
    },
    {
      id: 'thanni',
      tamil: 'தண்ணி',
      transliteration: 'taṇṇi',
      englishMeaning: 'Water (colloquial)',
      spanishMeaning: 'Agua (coloquial)',
      englishApproxPronunciation: 'TUN-nee',
      spanishApproxPronunciation: 'TA-ni',
      partOfSpeech: 'noun',
      tags: ['food', 'stage-1'],
      frequencyPriority: 31,
      difficulty: 1,
    },
    {
      id: 'theriyum',
      tamil: 'தெரியும்',
      transliteration: 'teriyum',
      englishMeaning: 'Know (it is known)',
      spanishMeaning: 'Saber (se sabe)',
      englishApproxPronunciation: 'theh-REE-yum',
      spanishApproxPronunciation: 'te-RI-um',
      partOfSpeech: 'verb',
      tags: ['verbs', 'stage-1'],
      frequencyPriority: 40,
      difficulty: 2,
    },
    {
      id: 'puriyala',
      tamil: 'புரியல',
      transliteration: 'puriyala',
      englishMeaning: "Don't understand (colloquial)",
      spanishMeaning: 'No entiendo (coloquial)',
      englishApproxPronunciation: 'pu-ri-YA-la',
      spanishApproxPronunciation: 'pu-ri-A-la',
      partOfSpeech: 'phrase',
      tags: ['verbs', 'stage-1'],
      frequencyPriority: 41,
      difficulty: 2,
    },
    {
      id: 'enna',
      tamil: 'என்ன',
      transliteration: 'eṉṉa',
      englishMeaning: 'What',
      spanishMeaning: 'Qué',
      englishApproxPronunciation: 'EN-nah',
      spanishApproxPronunciation: 'E-na',
      partOfSpeech: 'question',
      tags: ['questions', 'stage-1'],
      frequencyPriority: 50,
      difficulty: 1,
    },
    {
      id: 'enga',
      tamil: 'எங்க',
      transliteration: 'eṅka',
      englishMeaning: 'Where',
      spanishMeaning: 'Dónde',
      englishApproxPronunciation: 'ENG-gah',
      spanishApproxPronunciation: 'EN-ga',
      partOfSpeech: 'question',
      tags: ['questions', 'stage-1'],
      frequencyPriority: 51,
      difficulty: 1,
    },
    {
      id: 'yaaru',
      tamil: 'யாரு',
      transliteration: 'yāru',
      englishMeaning: 'Who (colloquial)',
      spanishMeaning: 'Quién (coloquial)',
      englishApproxPronunciation: 'YAA-ru',
      spanishApproxPronunciation: 'YA-ru',
      partOfSpeech: 'question',
      tags: ['questions', 'stage-1'],
      frequencyPriority: 52,
      difficulty: 2,
    },
    {
      id: 'eppadi',
      tamil: 'எப்படி',
      transliteration: 'eppaṭi',
      englishMeaning: 'How',
      spanishMeaning: 'Cómo',
      englishApproxPronunciation: 'EP-puh-dee',
      spanishApproxPronunciation: 'E-pa-di',
      partOfSpeech: 'question',
      tags: ['questions', 'stage-1'],
      frequencyPriority: 53,
      difficulty: 2,
    },
    {
      id: 'eppo',
      tamil: 'எப்போ',
      transliteration: 'eppō',
      englishMeaning: 'When (colloquial)',
      spanishMeaning: 'Cuándo (coloquial)',
      englishApproxPronunciation: 'EP-poh',
      spanishApproxPronunciation: 'E-po',
      partOfSpeech: 'question',
      tags: ['questions', 'stage-1'],
      frequencyPriority: 54,
      difficulty: 2,
    },
    {
      id: 'onnu',
      tamil: 'ஒண்ணு',
      transliteration: 'oṇṇu',
      englishMeaning: 'One (colloquial)',
      spanishMeaning: 'Uno (coloquial)',
      englishApproxPronunciation: 'OH-nnu',
      spanishApproxPronunciation: 'O-nu',
      partOfSpeech: 'number',
      tags: ['numbers', 'stage-1'],
      frequencyPriority: 60,
      difficulty: 1,
    },
    {
      id: 'rendu',
      tamil: 'ரெண்டு',
      transliteration: 'reṇṭu',
      englishMeaning: 'Two (colloquial)',
      spanishMeaning: 'Dos (coloquial)',
      englishApproxPronunciation: 'REN-du',
      spanishApproxPronunciation: 'REN-du',
      partOfSpeech: 'number',
      tags: ['numbers', 'stage-1'],
      frequencyPriority: 61,
      difficulty: 1,
    },
    {
      id: 'moonu',
      tamil: 'மூணு',
      transliteration: 'mūṇu',
      englishMeaning: 'Three (colloquial)',
      spanishMeaning: 'Tres (coloquial)',
      englishApproxPronunciation: 'MOO-nu',
      spanishApproxPronunciation: 'MU-nu',
      partOfSpeech: 'number',
      tags: ['numbers', 'stage-1'],
      frequencyPriority: 62,
      difficulty: 1,
    },
    {
      id: 'naalu',
      tamil: 'நாலு',
      transliteration: 'nālu',
      englishMeaning: 'Four (colloquial)',
      spanishMeaning: 'Cuatro (coloquial)',
      englishApproxPronunciation: 'NAH-lu',
      spanishApproxPronunciation: 'NA-lu',
      partOfSpeech: 'number',
      tags: ['numbers', 'stage-1'],
      frequencyPriority: 63,
      difficulty: 1,
    },
    {
      id: 'anju',
      tamil: 'அஞ்சு',
      transliteration: 'añcu',
      englishMeaning: 'Five (colloquial)',
      spanishMeaning: 'Cinco (coloquial)',
      englishApproxPronunciation: 'UN-ju',
      spanishApproxPronunciation: 'AN-chu',
      partOfSpeech: 'number',
      tags: ['numbers', 'stage-1'],
      frequencyPriority: 64,
      difficulty: 1,
    },
  ],
  stages: [
    {
      id: 'stage-1',
      orderIndex: 0,
      titleEn: 'Stage 1 — Survival conversation',
      titleEs: 'Etapa 1 — Conversación esencial',
      summaryEn:
        'Greetings, politeness, pronouns, essential verbs, questions, and numbers — combined for quick mini-dialogues.',
      summaryEs:
        'Saludos, cortesía, pronombres, verbos esenciales, preguntas y números — combinados para mini diálogos.',
      lessonIds: [
        's1-greetings',
        's1-polite-basics',
        's1-people-and-places',
        's1-verbs-needs',
        's1-questions-numbers',
      ],
    },
  ],
  lessons: [
    {
      id: 's1-greetings',
      stageId: 'stage-1',
      orderIndex: 0,
      titleEn: 'Hello and checking in',
      titleEs: 'Saludos y cómo estás',
      descriptionEn:
        'High-frequency greetings and responses you can use immediately in conversation.',
      descriptionEs:
        'Saludos y respuestas de muy alta frecuencia que puedes usar al instante.',
      newItemIds: [
        'vanakkam',
        'eppadi-irukeenga',
        'nalla-irukken',
        'sari',
        'aama',
        'illa',
      ],
      exerciseTypes: [
        'multiple_choice_meaning',
        'meaning_to_tamil',
        'transliteration_recognition',
        'word_matching',
        'fill_in_blank',
        'tap_order',
      ],
      estimatedMinutes: 8,
    },
    {
      id: 's1-polite-basics',
      stageId: 'stage-1',
      orderIndex: 1,
      titleEn: 'Thanks, sorry, please',
      titleEs: 'Gracias, perdón, por favor',
      descriptionEn: 'Politeness glue that makes Tamil sound natural and respectful.',
      descriptionEs: 'Cortesía que hace que el tamil suene natural y respetuoso.',
      newItemIds: ['nandri', 'mannikavum', 'thayavu-seithu'],
      exerciseTypes: [
        'multiple_choice_meaning',
        'meaning_to_tamil',
        'transliteration_recognition',
        'word_matching',
        'fill_in_blank',
        'tap_order',
      ],
      estimatedMinutes: 6,
    },
    {
      id: 's1-people-and-places',
      stageId: 'stage-1',
      orderIndex: 2,
      titleEn: 'I, you, we, here, there',
      titleEs: 'Yo, tú, nosotros, aquí, allí',
      descriptionEn: 'Core pronouns and location words for pointing and simple sentences.',
      descriptionEs: 'Pronombres básicos y de lugar para señalar y hacer frases simples.',
      newItemIds: [
        'naan',
        'neenga',
        'naanga',
        'avanga',
        'idhu',
        'adhu',
        'inga',
        'anga',
      ],
      exerciseTypes: [
        'multiple_choice_meaning',
        'meaning_to_tamil',
        'transliteration_recognition',
        'word_matching',
        'fill_in_blank',
        'tap_order',
      ],
      estimatedMinutes: 10,
    },
    {
      id: 's1-verbs-needs',
      stageId: 'stage-1',
      orderIndex: 3,
      titleEn: 'Going, coming, wanting, food and water',
      titleEs: 'Ir, venir, querer, comida y agua',
      descriptionEn: 'Mini phrases for movement, needs, and everyday nouns.',
      descriptionEs: 'Mini frases de movimiento, necesidades y sustantivos cotidianos.',
      newItemIds: [
        'poren',
        'vareen',
        'venum',
        'saapadu',
        'thanni',
        'theriyum',
        'puriyala',
      ],
      exerciseTypes: [
        'multiple_choice_meaning',
        'meaning_to_tamil',
        'transliteration_recognition',
        'word_matching',
        'fill_in_blank',
        'tap_order',
      ],
      estimatedMinutes: 10,
    },
    {
      id: 's1-questions-numbers',
      stageId: 'stage-1',
      orderIndex: 4,
      titleEn: 'Question words and numbers 1–5',
      titleEs: 'Palabras interrogativas y números 1–5',
      descriptionEn: 'Ask simple questions and handle small numbers in speech.',
      descriptionEs: 'Haz preguntas simples y maneja números pequeños al hablar.',
      newItemIds: [
        'enna',
        'enga',
        'yaaru',
        'eppadi',
        'eppo',
        'onnu',
        'rendu',
        'moonu',
        'naalu',
        'anju',
      ],
      exerciseTypes: [
        'multiple_choice_meaning',
        'meaning_to_tamil',
        'transliteration_recognition',
        'word_matching',
        'fill_in_blank',
        'tap_order',
      ],
      estimatedMinutes: 12,
    },
  ],
}
